version: 2.1
jobs:

  lint:
    docker:
      - image: cimg/node:20.16.0

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          key: node_modules-{{ checksum "yarn.lock" }}

      - run: test -d node_modules || yarn

      - save_cache:
          key: node_modules-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      # run tests!
      - run:
          command: yarn tslint && yarn lint

  unit:
    docker:
      - image: cimg/node:20.16.0

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          key: node_modules-{{ checksum "yarn.lock" }}

      - run: test -d node_modules || yarn

      - save_cache:
          key: node_modules-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      # run tests!
      - run:
          command: yarn unit


  integration:
    docker:
      - image: cimg/node:20.16.0

    environment:
      RETRY: "1"

    working_directory: ~/repo

    resource_class: large

    steps:
      - checkout

      - restore_cache:
          key: node_modules-{{ checksum "yarn.lock" }}

      - run: test -d node_modules || yarn

      - save_cache:
          key: node_modules-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      # run tests!
      - run:
          command: yarn jest || yarn jest || yarn jest || yarn jest

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - lint
      - unit
      - integration
