name: BuildReleaseTestflight

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      changelog:
        description: 'Changelog for TestFlight'
        required: false

jobs:
  build-and-prepare:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Cache Ruby Gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-

      - name: Cache CocoaPods
        uses: actions/cache@v2
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install dependencies with Bundler
        run: bundle install

      - name: Install Fastlane 2.217.0
        run: gem install fastlane -v 2.217.0

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Install node_modules
        run: npm install

      - name: Set up Git Authentication
        env:
          ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
        run: |
          git config --global credential.helper 'cache --timeout=3600'
          git config --global http.https://github.com/.extraheader "AUTHORIZATION: basic $(echo -n x-access-token:${ACCESS_TOKEN} | base64)"

      - name: Create Temporary Keychain
        run: bundle exec fastlane ios create_temp_keychain
        working-directory: ./ios
        env: 
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}

      - name: Setup Provisioning Profiles
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.GIT_ACCESS_TOKEN }}
          GIT_URL: ${{ secrets.GIT_URL }}
          ITC_TEAM_ID: ${{ secrets.ITC_TEAM_ID }}
          ITC_TEAM_NAME: ${{ secrets.ITC_TEAM_NAME }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: bundle exec fastlane ios setup_provisioning_profiles
        working-directory: ./ios

      - name: Clear Derived Data
        run: bundle exec fastlane ios clear_derived_data_lane
        working-directory: ./ios

      - name: Increment Build Number
        run: bundle exec fastlane ios increment_build_number_lane
        working-directory: ./ios

      - name: Install CocoaPods Dependencies
        run: bundle exec fastlane ios install_pods
        working-directory: ./ios

      - name: Build App
        run: bundle exec fastlane ios build_app_lane
        working-directory: ./ios
        env: 
          BRANCH_NAME: ${{ github.head_ref }}

      - name: Create App Store Connect API Key JSON
        run: echo '${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT }}' > ./ios/appstore_api_key.json

      - name: Get Latest Commit Message
        run: echo "LATEST_COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Read IPA Output Name
        id: ipa_name
        run: echo "::set-output name=ipa_output_name::$(cat output_name.txt)"

      - name: Upload IPA as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.ipa_name.outputs.ipa_output_name }}
          path: ./build/${{ steps.ipa_name.outputs.ipa_output_name }}

      - name: Upload Fastlane logs as Artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: fastlane-logs
          path: fastlane.log

  upload-to-testflight:
    needs: build-and-prepare
    if: github.event_name == 'workflow_dispatch'
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install Fastlane 2.217.0
        run: gem install fastlane -v 2.217.0

      - name: Upload to TestFlight
        run: bundle exec fastlane ios upload_to_testflight_lane changelog:"${{ github.event.inputs.changelog }}"
        working-directory: ./ios
